const addSchema={
  type:'Form',
  props:{
    name:'addForm',
    style:`{{width:'50%'}}`,
    '@rest':`{configs.layout}`,
  },
  children:[
    {
      type:'Item',
      props:{
        name:'name',
        label:'用户名',
        rules:'{self=>self.rules.nameRule}',
      },
      children:[
        {
          type:'Input',
          props:{
            placeholder:'用户名',
          },
        },
      ],
    },
    {
      type:'Item',
      props:{
        name:'email',
        label:'邮箱',
        rules:'{self=>self.rules.emailRule}',
      },
      children:[
        {
          type:'Input',
          props:{
            placeholder:'邮箱',
          },
        },
      ],
    },
    {
      type:'Item',
      props:{
        name:'password',
        label:'密码',
        rules:'{self=>self.rules.passwordRule}',
      },
      children:[
        {
          type:'Input',
          props:{
            placeholder:'密码',
            type:'password',
          },
        },
      ],
    },
    {
      type:'Item',
      props:{
        name:'role',
        label:'等级',
        rules:'{self=>self.rules.roleRule}',
      },
      children:[
        {
          type:'Select',
          props:{
            placeholder:'请选择',
            allowClear:true,
            options:'{configs.roleList}',
          },
        },
      ],
    },
    {
      type:'Item',
      props:{
        name:'avatar',
        label:'头像',
        rules:'',
      },
      children:[
        {
          type:'Input',
          props:{
            placeholder:'头像',
          },
        },
      ],
    },
    {
      type:'Item',
      props:{
        '@rest':'{configs.tailLayout}',
      },
      children:[
        {
          type:'Button',
          props:{
            type:'primary',
            htmlType:'submit',
            children:'保存',
          },
        },
        {
          type:'Button',
          props:{
            style:`{{marginLeft:'12px'}}`,
            onClick:'{self=>self.resetFields}',
            children:'重置',
          },
        },
      ],
    },
  ],
};

const schema={
  type:'Row',
  children:[
    {
      type:'Col',
      props:{
        span:12,
      },
      children:[
        {
          type:'Back',
        },
      ],
    },
    {
      type:'Col',
      props:{
        span:12,
      },
      children:[
        {
          type:'Panel',
          props:{},
          children:[
            {
              type:'CustomForm',
              props:{
                schema:addSchema,
              },
            },
          ],
        },
      ],
    },
  ],
};

export default schema;
