const objs = [
  {
    value: 'agile',
    label: '敏捷',
    icon: 'agile',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'algorithm',
    label: '算法',
    icon: 'algorithm',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'analysis',
    label: '分析',
    icon: 'analysis',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'api',
    label: ' API',
    icon: 'api',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'basketball',
    label: '篮球',
    icon: 'basketball',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'bigdata',
    label: '大数据',
    icon: 'bigdata',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'brain',
    label: '大脑',
    icon: 'brain',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'chat',
    label: '交流',
    icon: 'chat',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'checkup',
    label: '检查',
    icon: 'checkup',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'code',
    label: '代码',
    icon: 'code',
    details: '',
    link: '',
    type: '',
  },

  {
    value: 'coder',
    label: '码农',
    icon: 'coder',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'cogwheel',
    label: '齿轮',
    icon: 'cogwheel',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'control',
    label: '控制',
    icon: 'control',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'css',
    label: ' CSS',
    icon: 'css',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'dashboard',
    label: '仪表板',
    icon: 'dashboard',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'dataAnalysis',
    label: '数据分析',
    icon: 'dataAnalysis',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'dataModelling',
    label: '建模',
    icon: 'dataModelling',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'debug',
    label: '调试',
    icon: 'debug',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'diagram',
    label: '图表',
    icon: 'diagram',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'digital',
    label: '数字化',
    icon: 'digital',
    details: '',
    link: '',
    type: '',
  },

  {
    value: 'flow',
    label: '流程',
    icon: 'flow',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'html',
    label: ' HTML',
    icon: 'html',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'js',
    label: 'Javascript',
    icon: 'js',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'light',
    label: '灯光',
    icon: 'light',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'lineChart',
    label: '折线图',
    icon: 'lineChart',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'manufacturing',
    label: '制造',
    icon: 'manufacturing',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'map',
    label: '地图',
    icon: 'map',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'monitoring',
    label: '监控',
    icon: 'monitoring',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'notFound',
    label: '404',
    icon: 'notFound',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'organization',
    label: '组织',
    icon: 'organization',
    details: '',
    link: '',
    type: '',
  },

  {
    value: 'production',
    label: '生产',
    icon: 'production',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'programming',
    label: '编程',
    icon: 'programming',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'screen',
    label: '大屏',
    icon: 'screen',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'setting',
    label: '设置',
    icon: 'setting',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'simulation',
    label: '模拟',
    icon: 'simulation',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'time',
    label: '时间',
    icon: 'time',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'trend',
    label: '趋势',
    icon: 'trend',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'webAnalysis',
    label: '网络分析',
    icon: 'webAnalysis',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'workHome',
    label: '在家工作',
    icon: 'workHome',
    details: '',
    link: '',
    type: '',
  },
  {
    value: 'write',
    label: '编写',
    icon: 'write',
    details: '',
    link: '',
    type: '',
  },
];

export default objs;
