export const commonRoutes={
  path:'/commons',
  name:' Common',
  icon:'ShopOutlined',
  children:[
    {
      path:'/suspense',
      name:'suspense',
      icon:'CoffeeOutlined',
      children:[
        {
          path:'/suspense',
          name:'suspense',
          componentPath:'/commons/suspense',
        },
        {
          path:'/errorboundary',
          name:'errorboundary',
          componentPath:'/commons/suspense/errorboundary',
        },
      ],
    },
    {
      path:'/canvas',
      name:'图形绘制',
      icon:'AreaChartOutlined',
      children:[
        {
          path:'/canvas',
          name:'canvas',
          componentPath:'/commons/canvas',
        },
        {
          path:'/d3',
          name:'d3',
          componentPath:'/commons/canvas/d3',
        },
        {
          path:'/webgl',
          name:'webgl',
          componentPath:'/commons/canvas/webgl',
        },
        {
          path:'/dragable',
          name:'dragable',
          componentPath:'/commons/canvas/dragable',
        },
      ],
    },
    {
      path:'/graph',
      name:'图形可视化',
      icon:'FundOutlined',
      componentPath:'/commons/graph/graphin',
    },
    {
      path:'/editor',
      name:'富文本编辑器',
      icon:'EditOutlined',
      componentPath:'/commons/slate/test1',
    },
    {
      path:'/virtualList',
      name:'虚拟列表',
      icon:'UnorderedListOutlined',
      componentPath:'/commons/virtualList',
    },
    {
      path:'/components',
      name:'组件',
      icon:'LayoutOutlined',
      children:[
        {
          path:'/table',
          name:'table',
          icon:'TableOutlined',
          componentPath:'/apps/users',
        },
        {
          path:'/table/add',
          name:'添加用户',
          hideMenu:true,
          componentPath:'/apps/users/add',
        },
        {
          path:'/table/edit/:id',
          name:'编辑用户',
          componentPath:'/apps/users/add',
        },
      ],
    },
  ],
};
export const dashboardRoutes={
  path:'/dashboard',
  name:'仪表盘',
  icon:'HomeOutlined',
  children:[
    {
      path:'/screen1',
      name:'screen1',
      icon:'DashboardOutlined',
      componentPath:'/dashboard/screen1',
    },
    {
      path:'/screen2',
      name:'screen2',
      icon:'DashboardOutlined',
      componentPath:'/dashboard/screen2',
    },
  ],
};
export const configRoutes={
  path:'/layout',
  name:'框架配置',
  icon:'LayoutOutlined',
  componentPath:'/layout',
};

export const pageRoutes={
  path:'/page1',
  name:'一级菜单',
  icon:'FileTextOutlined',
  children:[
    {
      path:'/page1-1',
      name:'二级菜单1',
      componentPath:'/page',
    },
    {
      path:'/page1-2',
      name:'二级菜单2',
      children:[
        {
          path:'/page1-2-1',
          name:'三级菜单1',
          icon:'RobotOutlined',
          componentPath:'/page',
        },
        {
          path:'/page1-2-2',
          name:'三级菜单2',
          children:[
            {
              path:'/page1-2-2-1',
              name:'四级菜单1',
              componentPath:'/page',
            },
            {
              path:'/page1-2-2-2',
              name:'四级菜单1-disabled',
              componentPath:'/page',
              linkProps:{
                disabled:true,
              },
            },
            {
              path:'/page1-2-2-3',
              name:'四级菜单3-_blank',
              componentPath:'/page',
              linkProps:{
                target:'_blank',
              },
            },
          ],
        },
      ],
    },
    {
      path:'/page1-3',
      name:'二级菜单3',
      icon:'RobotOutlined',
      componentPath:'/page',
    },
  ],
};
export const playgroundRoutes={
  path:'/playground',
  name:' Playground',
  icon:'ConsoleSqlOutlined',
  children:[
    {
      path:'/icons',
      name:'icons',
      icon:'PictureOutlined',
      componentPath:'/demo/icons',
    },
  ],
};




