name: CI
on:
  push:
    branches:
      - develop
    paths-ignore:
      - LICENSE
      - README.md
      - 'doc/**'
      - 'configs/**'
      - 'scripts/**'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 同步到 gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SERVER_KEY }}
        with:
          source-repo: git@github.com:ahyiru/ihuxy.git
          destination-repo: git@gitee.com:yiru/ihuxy.git
